version: '3.7'

services:
  adminer:
    env_file: .env
    build:
      dockerfile: ./Dockerfile
      context: ./adminer
    ports:
      - 8000:8080

  mysql:
    env_file: .env
    build:
      dockerfile: ./Dockerfile
      context: ./mysql
    volumes:
      - mysql-data:/var/lib/mysql

  sqlite:
    env_file: .env
    stdin_open: true
    tty: true
    build:
      dockerfile: ./Dockerfile
      context: ./sqlite
    volumes:
      - sqlite-data:/databases

  postgresql:
    env_file: .env
    build:
      dockerfile: ./Dockerfile
      context: ./postgresql
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  mysql-data:
  sqlite-data:
  postgresql-data:
